# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: npm publish --access public

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
  publish:
    jobs:
      - deploy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d\.\d\.\d/
